### ISSUE TITLE
Do twinkly squares work at all

### ISSUE THREAD

**Issue by xnopasaranx** [cgorski/glow-control#30]
I cannot get the CLI tool to find my twinkly square controller. I have no VLAN and all my devices are on the same subnet, I should think it would be discoverable. Even with a timeout increased to 10000ms, no dice. I cannot find anything reliable about what devices are supported, had the same issue with xled/xled_plus. Maybe the latest firmware is the culprit, as they apparently updated their API to v4 recently.

**Comment by xnopasaranx** [comment]
for completeness: the squares have been set up with the official app. They are displaying GIFs and effects just fine through twinklys closed source app.

**Comment by xnopasaranx** [comment]
After some more testing, I conclude that squares are not supported. I can get the mode with the IP and mac address, but the test example only shows a static red color on all tiles with no animation. So it's doing something, but not what I am intending to do.

**Comment by JanDiederich** [comment]
It's working nicely with my Twinkly Squares (2nd generation). I found the documentation enough and most methods self-explaining.
I'm working right now on an open library (based on this library), to send complete images to the Squares.

The library version I use is based on 0.4.0. I made _enhancements_ to it, the basic version was already working for me.

**Comment by cgorski** [comment]
@xnopasaranx, thanks for your feedback. @JanDiederich I added issue #32 for verification and example submission for twinkly square operation. Any contributions would be much appreciated.
